<?php

namespace Statikbe\FilamentFlexibleContentBlocks\Filament\Form\Fields;

use Filament\Forms\Components\Grid;

class OverviewFields extends Grid
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->childComponents = [
            OverviewTitleField::create(),
            OverviewDescriptionField::create(),
            OverviewImageField::create(),
        ];
    }
}
